import React, { useMemo, useState } from 'react';
import { buildAnalytics } from '../analyticsData.js';

const Card=({label,value,tone='blue'})=><div className={`rounded-2xl border bg-${tone}-50 border-${tone}-100 p-3`}><div className="text-[10px] font-bold text-slate-500">{label}</div><div className="text-2xl font-black text-slate-800 mt-1">{value}</div></div>;
const Bar=({label,a,b,max})=><div className="grid grid-cols-[38px_1fr_56px] gap-2 items-center text-[10px]"><b>{label}</b><div className="h-3 bg-slate-100 rounded-full overflow-hidden flex"><i className="bg-blue-500" style={{width:`${a/max*100}%`}}/><i className="bg-rose-400" style={{width:`${b/max*100}%`}}/></div><span className="text-right"><b className="text-blue-600">{a}</b> / <b className="text-rose-500">{b}</b></span></div>;

export default function AnalyticsHub({ db, notes, onNotesChange, onClose }) {
  const [tab,setTab]=useState('dashboard'); const [teamId,setTeamId]=useState(db.teams[0]?.id||''); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [opponentId,setOpponentId]=useState(''); const [gameType,setGameType]=useState('ALL'); const [playerId,setPlayerId]=useState('');
  const stats=useMemo(()=>buildAnalytics(db,{teamId,from,to,opponentId,gameType,playerId}),[db,teamId,from,to,opponentId,gameType,playerId]);
  const opponents=db.teams.filter(t=>t.id!==teamId); const max=Math.max(1,...stats.innings.flatMap(x=>[x.for,x.against])); const selected=stats.players.find(p=>p.id===playerId)||stats.players[0];
  const gamesForPlayer=selected?db.plateAppearances.filter(pa=>(pa.batterId===selected.id||pa.pitcherId===selected.id)&&stats.games.some(g=>g.id===pa.gameId)):[];
  return <div className="fixed inset-0 z-[700] bg-slate-950/80 backdrop-blur-sm p-0 md:p-4"><div className="bg-slate-50 h-full max-w-6xl mx-auto md:rounded-3xl overflow-hidden flex flex-col shadow-2xl">
    <header className="bg-slate-900 text-white p-4 flex items-center justify-between"><div><h2 className="font-black text-lg">分析ハブ</h2><p className="text-[10px] text-slate-300">生の試合記録からいつでも再集計</p></div><button onClick={onClose} className="text-2xl px-2">×</button></header>
    <nav className="grid grid-cols-3 bg-white border-b p-2 gap-2">{[['dashboard','自チーム分析'],['players','選手カルテ'],['opponent','対戦相手']].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`py-2 rounded-xl text-xs font-black ${tab===k?'bg-blue-600 text-white':'bg-slate-100 text-slate-600'}`}>{l}</button>)}</nav>
    <div className="p-3 bg-white border-b flex flex-wrap gap-2"><select value={teamId} onChange={e=>{setTeamId(e.target.value);setPlayerId('');}} className="filter-input"><option value="">チーム</option>{db.teams.map(t=><option key={t.id} value={t.id}>{t.role==='own'?'自':'相手'}｜{t.name}</option>)}</select><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="filter-input"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="filter-input"/><select value={gameType} onChange={e=>setGameType(e.target.value)} className="filter-input"><option value="ALL">全試合種別</option>{[...new Set(db.games.map(g=>g.gameType))].map(x=><option key={x}>{x}</option>)}</select><select value={opponentId} onChange={e=>setOpponentId(e.target.value)} className="filter-input"><option value="">全対戦相手</option>{opponents.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div>
    <main className="flex-1 overflow-y-auto p-4 space-y-4">
      {tab==='dashboard'&&<><div className="grid grid-cols-2 md:grid-cols-6 gap-2"><Card label="試合" value={stats.games.length}/><Card label="勝敗" value={`${stats.wins}勝 ${stats.losses}敗`}/><Card label="得失点" value={`${stats.runsFor}-${stats.runsAgainst}`}/><Card label="出塁率" value={stats.batting.OBP||'.000'}/><Card label="長打率" value={stats.batting.SLG||'.000'}/><Card label="OPS" value={stats.batting.OPS||'.000'}/><Card label="三振率" value={`${stats.batting.KPct||0}%`}/><Card label="四球率" value={`${stats.batting.BBPct||0}%`}/><Card label="被打率" value={stats.pitching.AVG||'.000'}/><Card label="WHIP目安" value={stats.pitching.WHIP||'0.000'}/><Card label="初球ストライク" value={`${stats.pitching.firstStrikePct||0}%`}/><Card label="失策" value={db.fieldingEvents.filter(e=>stats.games.some(g=>g.id===e.gameId)&&e.teamId===teamId).length}/></div><section className="panel"><h3>イニング別得失点</h3><div className="space-y-2 mt-3">{stats.innings.map(x=><Bar key={x.inning} label={`${x.inning}回`} a={x.for} b={x.against} max={max*2}/>)}</div><div className="text-[10px] mt-3"><span className="text-blue-600">■ 得点</span>　<span className="text-rose-500">■ 失点</span></div></section><section className="grid md:grid-cols-3 gap-2">{stats.patterns.map(p=><Card key={p.label} label={p.label} value={p.value}/>)}</section></>}
      {tab==='players'&&<><select value={selected?.id||''} onChange={e=>setPlayerId(e.target.value)} className="w-full p-3 rounded-xl border font-bold"><option value="">選手を選択</option>{stats.players.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{selected?<><div className="grid grid-cols-2 md:grid-cols-6 gap-2"><Card label="打席" value={selected.PA}/><Card label="打率" value={selected.AVG}/><Card label="出塁率" value={selected.OBP}/><Card label="長打率" value={selected.SLG}/><Card label="OPS" value={selected.OPS}/><Card label="奪三振" value={selected.SO}/></div><section className="panel"><h3>直近傾向・試合別記録</h3><div className="mt-3 space-y-2">{stats.games.slice(-8).reverse().map(g=>{const rows=gamesForPlayer.filter(pa=>pa.gameId===g.id);return <div key={g.id} className="flex justify-between border-b py-2 text-xs"><span>{g.date}　{g.teamTop} vs {g.teamBottom}</span><b>{rows.length}記録</b></div>})}</div></section><section className="panel"><h3>育成メモ</h3><textarea value={notes[selected.id]||''} onChange={e=>onNotesChange({...notes,[selected.id]:e.target.value})} placeholder="長所、課題、練習方針、次回確認すること…" className="w-full min-h-32 mt-3 p-3 border rounded-xl text-sm"/></section></>:<p className="empty">記録のある選手がいません</p>}</>}
      {tab==='opponent'&&<>{stats.team&&<section className="panel border-l-4 border-l-rose-500"><h3>スカウティングレポート｜{stats.team.name}</h3><p className="text-xs text-slate-500 mt-1">複数試合の累計（{stats.games.length}試合）</p><div className="grid grid-cols-2 md:grid-cols-5 gap-2 mt-4"><Card label="得点 / 失点" value={`${stats.runsFor} / ${stats.runsAgainst}`}/><Card label="OPS" value={stats.batting.OPS}/><Card label="三振率" value={`${stats.batting.KPct}%`}/><Card label="四球率" value={`${stats.batting.BBPct}%`}/><Card label="初球S率" value={`${stats.pitching.firstStrikePct}%`}/></div></section>}<section className="panel"><h3>打者別の警戒度</h3><div className="mt-2 space-y-2">{stats.players.sort((a,b)=>Number(b.OPS)-Number(a.OPS)).map(p=><div key={p.id} className="grid grid-cols-[1fr_50px_60px_60px] text-xs border-b py-2"><b>{p.name}</b><span>{p.PA}打席</span><span>OPS {p.OPS}</span><span>K {p.K}</span></div>)}</div></section><section className="panel"><h3>傾向メモ</h3><p className="text-xs text-slate-600 mt-2">打球方向・カウント・左右・バント・盗塁は、各試合の記録項目が入力されている範囲で正規化データに蓄積されます。</p></section></>}
    </main></div></div>;
}
